# Wine class Classification

In [1]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/rohithsukka/DataSets/main/wine.csv')

df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6        127           2.80   
1    13.20        1.78  2.14               11.2        100           2.65   
2    13.16        2.36  2.67               18.6        101           2.80   
3    14.37        1.95  2.50               16.8        113           3.85   
4    13.24        2.59  2.87               21.0        118           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  Target  
0                          3.92     1065       0  
1                          3.40     1050       0  
2                          3.17     1185       0  
3                          3.45     1480       0  
4                          2.93      735       0

In [2]:
df['Target'].value_counts()

Target
1    71
0    59
2    48
Name: count, dtype: int64

In [3]:
#Build and evaluate a classification model to identify the class of wine based on given featuers

X = df.drop('Target' , axis = 'columns')
Y = df['Target']

#split the data into train & test
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest = train_test_split(X,Y)

#build a ml model

from sklearn.neighbors import KNeighborsClassifier

model1 = KNeighborsClassifier(n_neighbors = 5)

model1.fit(xtrain,ytrain)

#Evalaute model performance

print("Accuracy on training data" , model1.score(xtrain,ytrain))
print("Accuracy on test data" , model1.score(xtest,ytest))

Accuracy on training data 0.7518796992481203
Accuracy on test data 0.8222222222222222


**Build a model after performing data scaling**

In [4]:
import numpy as np

n1 = np.array([2,5,1,7,9])

n1_scaled = (n1-n1.min())/(n1.max() - n1.min())
print(n1_scaled)

[0.125 0.5   0.    0.75  1.   ]


In [5]:
X = df.drop('Target' , axis = 'columns')
Y = df['Target']

#Data Scaling
from sklearn.preprocessing import MinMaxScaler
scl = MinMaxScaler()

X_scaled = scl.fit_transform(X)

#split the data into train & test
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest = train_test_split(X_scaled,Y)

#build a ml model

from sklearn.neighbors import KNeighborsClassifier

model2 = KNeighborsClassifier(n_neighbors = 5)

model2.fit(xtrain,ytrain)

#Evalaute model performance

print("Accuracy on training data" , model2.score(xtrain,ytrain))
print("Accuracy on test data" , model2.score(xtest,ytest))

Accuracy on training data 0.9699248120300752
Accuracy on test data 0.9555555555555556


In [7]:
#predictions 
print(xtest[9])

print()

model2.predict([xtest[9]])

[0.34473684 0.33794466 0.58823529 0.53608247 0.30434783 0.54482759
 0.37341772 0.39622642 0.28391167 0.12969283 0.2601626  0.77289377
 0.11412268]



array([1], dtype=int64)

In [8]:
X.head(3)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6        127           2.80   
1    13.20        1.78  2.14               11.2        100           2.65   
2    13.16        2.36  2.67               18.6        101           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   

   od280/od315_of_diluted_wines  proline  
0                          3.92     1065  
1                          3.40     1050  
2                          3.17     1185

In [10]:
X.values[2]

array([1.316e+01, 2.360e+00, 2.670e+00, 1.860e+01, 1.010e+02, 2.800e+00,
       3.240e+00, 3.000e-01, 2.810e+00, 5.680e+00, 1.030e+00, 3.170e+00,
       1.185e+03])

In [12]:
scl.transform([X.values[2]])

C:\Users\rohit\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0.56052632, 0.3201581 , 0.70053476, 0.41237113, 0.33695652,
        0.62758621, 0.61181435, 0.32075472, 0.75709779, 0.37542662,
        0.44715447, 0.6959707 , 0.64693295]])

In [13]:
print(model2.predict(scl.transform([X.values[2]])))

[0]


C:\Users\rohit\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
